name: FoxBukkitChat
main: com.foxelbox.foxbukkit.chat.FoxBukkitChat
version: 1.3.0
commands:
  me:
    description: /me
    permission: foxbukkit.me
    usage: /<command>
    aliases:
      - action
  ignore:
    description: Ignore system management
    permission: foxbukkit.ignore
    usage: /<command> [add/remove/list/clear] Player
  pm:
    description: Private message
    permission: foxbukkit.pm
    usage: /<command>
    aliases:
      - whisper
      - tell
  reloadchat:
    description: Reload chat
    permission: foxbukkit.reloadchat
    usage: /<command>
